### PR TITLE
cmake_fixes

### PR DESCRIPTION
**Pull request by a-teammate**
some small fixes, mainly cleaning up the cmake files.
(+ making it ready for karo/tree_gen, fixing issue #286 and other cleanups, also regarding the cmake gui)

### CODE REVIEW

**Comment by bebehei** [comment]
Building on ArchLinux:
```
../filesystem/libmodule_filesystem.a(mediadirs.cpp.o): In function `inexor::filesystem::getmediapath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/home/bebe/code/inexor/inexor/filesystem/mediadirs.cpp:41: undefined reference to `inexor::util::fmt'
collect2: error: ld returned 1 exit status
inexor/master/CMakeFiles/master.dir/build.make:270: recipe for target 'inexor/master/master' failed
make[2]: *** [inexor/master/master] Error 1
CMakeFiles/Makefile2:733: recipe for target 'inexor/master/CMakeFiles/master.dir/all' failed
make[1]: *** [inexor/master/CMakeFiles/master.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

But the latest master works fine.

**Comment by bebehei** [comment]
With `git bisect`, I got the commit: c1ce3f4eeb8c598ea56d7d2940751ee9355f8318 (cmake: add pragma_once to all require_ functions to make output readable.)

@a-teammate do you have any clue?

**Comment by a-teammate** [comment]
what pragma once does it "requires" every module only one time and then remembers and bypasses it for every following requiring-attempts.
Thanks, i know the bug now, its actually more surprising that it does work for me^^

**Comment by bebehei** [comment]
> Could you maybe provide a list of the output from your cmake?
Especially the part coming after the line "THREADAPI: "..

Here it is:

```
[...]
-- glibc ABI workaround: Registering lib dependency: /usr/lib64/libpthread.so
-- THREADAPI : pthreads
-- Found OpenGL: /usr/lib64/libGL.so  
-- glibc ABI workaround: Registering lib dependency: /usr/lib64/libSDL2.so;/usr/lib64/libSDL2_image.so;/usr/lib64/libSDL2_mixer.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- glibc ABI workaround: Registering lib dependency: /usr/lib64/libz.so
-- glibc ABI workaround: Registering lib dependency: /usr/lib64/libenet.so
-- glibc ABI workaround: Registering lib dependency: /usr/lib64/libboost_system.so
-- glibc ABI workaround: Registering lib dependency: /usr/lib64/libboost_thread.so
-- glibc ABI workaround: Registering lib dependency: /usr/lib64/libboost_random.so
-- glibc ABI workaround: Registering lib dependency: /usr/lib64/libboost_filesystem.so
-- glibc ABI workaround: Registering lib dependency: /usr/lib64/libprotobuf.so
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start
-- /usr/lib64/libpthread.so requires new GLIBC C++11 ABI: no
-- /usr/lib64/libSDL2.so requires new GLIBC C++11 ABI: no
-- /usr/lib64/libSDL2_image.so requires new GLIBC C++11 ABI: no
-- /usr/lib64/libSDL2_mixer.so requires new GLIBC C++11 ABI: no
-- /usr/lib64/libz.so requires new GLIBC C++11 ABI: no
-- /usr/lib64/libenet.so requires new GLIBC C++11 ABI: no
-- /usr/lib64/libboost_system.so requires new GLIBC C++11 ABI: yes
-- /usr/lib64/libboost_thread.so requires new GLIBC C++11 ABI: yes
-- /usr/lib64/libboost_random.so requires new GLIBC C++11 ABI: yes
-- /usr/lib64/libboost_filesystem.so requires new GLIBC C++11 ABI: yes
-- /usr/lib64/libprotobuf.so requires new GLIBC C++11 ABI: yes
-- Compiling with new GLIBC C++11 ABI: yes
[...]
```
